name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 1.0.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_dotenv: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  nylo_support: ^1.0.0
  adaptive_theme: ^2.2.0
  args: ^2.0.0
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

