name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 0.4.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  json_to_dart: ^1.0.4
  flutter_launcher_icons: ^0.8.0
  queue: ^2.0.5
  dynamic_theme: ^1.0.1
  sailor: ^0.7.1
  flutter_secure_storage: ^3.3.3
  flutter_dotenv: ^2.1.0
  args: ^1.6.0
  connectivity: ^0.4.9+2
  logger: ^0.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

