name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 0.8.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_launcher_icons: ^0.9.0
  page_transition: ^2.0.1-nullsafety.0
  queue: ^3.1.0
  adaptive_theme: ^2.0.1
  flutter_secure_storage: ^4.1.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  args: ^2.0.0
  logger: ^1.0.0
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

